import connection.DatabaseConnection;
import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.sql.Connection;
import java.sql.DriverManager;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Matheesha Anjana
 */
public class GpuForm extends javax.swing.JFrame {

    /**
     * Creates new form GpuForm
     */
    public GpuForm() {
        initComponents();
    }
    
    private void loadStudentDetails(int studentId) {
    try {
        Connection con = DatabaseConnection.getConnection();
        String sql = "SELECT * FROM student WHERE student_id = ?";
        PreparedStatement stmt = con.prepareStatement(sql);
        stmt.setInt(1, studentId);
        ResultSet rs = stmt.executeQuery();

        if (rs.next()) {
            lblShowStID.setText(String.valueOf(rs.getInt("student_id")));
            lblShowtxtName.setText(rs.getString("student_name"));
            lblShowEmail.setText(rs.getString("email"));
            lblShowPhoneNo.setText(rs.getString("phone_number"));
        } else {
            lblShowStID.setText("---");
            lblShowtxtName.setText("---");
            lblShowEmail.setText("---");
            lblShowPhoneNo.setText("---");
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblShowtxtName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblShowEmail = new javax.swing.JLabel();
        lblShowPhoneNo = new javax.swing.JLabel();
        lblShowStID = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnCalculate = new javax.swing.JButton();
        txtStudentIdRecorection = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblGpuUpdate = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-back-24.png"))); // NOI18N
        jLabel8.setText("Student Grade Management System");
        jLabel8.setIconTextGap(20);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, 30));

        jLabel9.setBackground(new java.awt.Color(0, 8, 28));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-account-24.png"))); // NOI18N
        jLabel9.setText("Welcome, User");
        jLabel9.setIconTextGap(6);
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 140, 30));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 50));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(5, 8, 28));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblShowtxtName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblShowtxtName.setForeground(new java.awt.Color(204, 0, 0));
        lblShowtxtName.setText("---");
        jPanel6.add(lblShowtxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 20));

        jLabel5.setForeground(new java.awt.Color(204, 204, 255));
        jLabel5.setText("Phone No :");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 255));
        jLabel10.setText("Student Details");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel11.setForeground(new java.awt.Color(204, 204, 255));
        jLabel11.setText("Student Name :");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel12.setForeground(new java.awt.Color(204, 204, 255));
        jLabel12.setText("Email :");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel13.setForeground(new java.awt.Color(204, 204, 255));
        jLabel13.setText("Student ID :");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        lblShowEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblShowEmail.setForeground(new java.awt.Color(204, 0, 0));
        lblShowEmail.setText("---");
        jPanel6.add(lblShowEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        lblShowPhoneNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblShowPhoneNo.setForeground(new java.awt.Color(204, 0, 0));
        lblShowPhoneNo.setText("---");
        jPanel6.add(lblShowPhoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        lblShowStID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblShowStID.setForeground(new java.awt.Color(204, 0, 0));
        lblShowStID.setText("---");
        jPanel6.add(lblShowStID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 240, 270));

        jPanel2.setBackground(new java.awt.Color(5, 8, 28));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCalculate.setBackground(new java.awt.Color(255, 204, 0));
        btnCalculate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCalculate.setForeground(new java.awt.Color(255, 255, 255));
        btnCalculate.setText("Calculate");
        btnCalculate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateActionPerformed(evt);
            }
        });
        jPanel2.add(btnCalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 250, -1));

        txtStudentIdRecorection.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtStudentIdRecorectionKeyReleased(evt);
            }
        });
        jPanel2.add(txtStudentIdRecorection, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 250, -1));

        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("Enter student id");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("Calculate GPU");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 370));

        jPanel3.setBackground(new java.awt.Color(5, 8, 28));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGpuUpdate.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblGpuUpdate.setForeground(new java.awt.Color(204, 0, 0));
        lblGpuUpdate.setText("00.00");
        jPanel3.add(lblGpuUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 255));
        jLabel15.setText("GPU");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 220, 270));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 880, 370));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        studentDashboard obj0 = new studentDashboard();
        obj0.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void txtStudentIdRecorectionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStudentIdRecorectionKeyReleased
         try {
            int sid = Integer.parseInt(txtStudentIdRecorection.getText().trim());
            loadStudentDetails(sid);
        } catch (NumberFormatException ex) {
            txtStudentIdRecorection.setText("");
        }                // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentIdRecorectionKeyReleased

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed
      if (txtStudentIdRecorection.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a student ID.");
        return;
    }

    try {
        int studentId = Integer.parseInt(txtStudentIdRecorection.getText());
        Connection con = DatabaseConnection.getConnection();
        String sql = "SELECT AVG(marks) AS average_marks FROM result_grade WHERE student_id = ?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setInt(1, studentId);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            double avg = rs.getDouble("average_marks");
            lblGpuUpdate.setText(String.format("%.2f", avg)); // Format to 2 decimals
        } else {
            lblGpuUpdate.setText("00.00");
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid student ID.");
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error calculating average.");
    }       
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalculateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GpuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GpuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GpuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GpuForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GpuForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblGpuUpdate;
    private javax.swing.JLabel lblShowEmail;
    private javax.swing.JLabel lblShowPhoneNo;
    private javax.swing.JLabel lblShowStID;
    private javax.swing.JLabel lblShowtxtName;
    private javax.swing.JTextField txtStudentIdRecorection;
    // End of variables declaration//GEN-END:variables
}
