import connection.DatabaseConnection;
import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.sql.Connection;
import java.sql.DriverManager;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Matheesha Anjana
 */
public class gradeForm extends javax.swing.JFrame {

    /**
     * Creates new form gradeForm
     */
    public gradeForm() {
        initComponents();
        loadResultData();
    }
    private void loadResultData() {
    // Get the model from the table component (assumed to be pnlGradeDetail)
    DefaultTableModel model = (DefaultTableModel) pnlGradeDetails.getModel(); 

    // Set column headers (if not already defined)
    model.setColumnIdentifiers(new String[] {
        "Student ID", "Subject ID", "Marks", "Grade"
    });

    model.setRowCount(0); // Clear existing rows

    try {
        Connection con = DatabaseConnection.getConnection();
        String sql = "SELECT * FROM result_grade";
        Statement stmt = con.createStatement();
        ResultSet rs = stmt.executeQuery(sql);

        while (rs.next()) {
            String studentId = rs.getString("student_id");
            String subjectId = rs.getString("subject_id");
            String grade = rs.getString("grade");
            String marks = rs.getString("marks");

            model.addRow(new Object[]{studentId, subjectId, marks, grade});
        }

        // ✅ No need for: pnlReport.setmodel(model); — the table is already updated
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error loading result data: " + e.getMessage());
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSubjectIdGrade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnclearGrade = new javax.swing.JButton();
        btnUpdateGrade = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbGrade = new javax.swing.JComboBox<>();
        btnDeleteGrade1 = new javax.swing.JButton();
        btnAddGrade3 = new javax.swing.JButton();
        txtStudentIdGrade1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lblShowtxtName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblShowEmail = new javax.swing.JLabel();
        lblShowPhoneNo = new javax.swing.JLabel();
        lblShowStID = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblShowSubjectId = new javax.swing.JLabel();
        lblShowSubjectName = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pnlGradeDetails = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtMarksGrade = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(5, 8, 28));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("Student ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        txtSubjectIdGrade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSubjectIdGradeKeyReleased(evt);
            }
        });
        jPanel1.add(txtSubjectIdGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 310, -1));

        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("Subject ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        btnclearGrade.setBackground(new java.awt.Color(5, 8, 28));
        btnclearGrade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnclearGrade.setForeground(new java.awt.Color(255, 255, 255));
        btnclearGrade.setText("Clear");
        btnclearGrade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnclearGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearGradeActionPerformed(evt);
            }
        });
        jPanel1.add(btnclearGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 310, -1));

        btnUpdateGrade.setBackground(new java.awt.Color(255, 204, 0));
        btnUpdateGrade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdateGrade.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateGrade.setText("update");
        btnUpdateGrade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateGradeActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdateGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 310, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("Grade");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, -1, -1));

        jLabel10.setForeground(new java.awt.Color(204, 204, 255));
        jLabel10.setText("Grade");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        cmbGrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D+", "D", "D-" }));
        jPanel1.add(cmbGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 310, -1));

        btnDeleteGrade1.setBackground(new java.awt.Color(255, 204, 0));
        btnDeleteGrade1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteGrade1.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteGrade1.setText("Delete");
        btnDeleteGrade1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteGrade1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteGrade1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteGrade1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteGrade1MouseExited(evt);
            }
        });
        btnDeleteGrade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteGrade1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeleteGrade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 310, -1));

        btnAddGrade3.setBackground(new java.awt.Color(255, 204, 0));
        btnAddGrade3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddGrade3.setForeground(new java.awt.Color(255, 255, 255));
        btnAddGrade3.setText("Add");
        btnAddGrade3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddGrade3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddGrade3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddGrade3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 310, -1));

        txtStudentIdGrade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentIdGrade1ActionPerformed(evt);
            }
        });
        txtStudentIdGrade1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtStudentIdGrade1KeyReleased(evt);
            }
        });
        jPanel1.add(txtStudentIdGrade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 310, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblShowtxtName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblShowtxtName.setForeground(new java.awt.Color(204, 0, 0));
        lblShowtxtName.setText("---");
        jPanel3.add(lblShowtxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 20));

        jLabel5.setForeground(new java.awt.Color(204, 204, 255));
        jLabel5.setText("Phone No :");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 255));
        jLabel6.setText("Student Details");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel11.setForeground(new java.awt.Color(204, 204, 255));
        jLabel11.setText("Student Name :");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel12.setForeground(new java.awt.Color(204, 204, 255));
        jLabel12.setText("Email :");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel13.setForeground(new java.awt.Color(204, 204, 255));
        jLabel13.setText("Student ID :");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        lblShowEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblShowEmail.setForeground(new java.awt.Color(204, 0, 0));
        lblShowEmail.setText("---");
        jPanel3.add(lblShowEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        lblShowPhoneNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblShowPhoneNo.setForeground(new java.awt.Color(204, 0, 0));
        lblShowPhoneNo.setText("---");
        jPanel3.add(lblShowPhoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        lblShowStID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblShowStID.setForeground(new java.awt.Color(204, 0, 0));
        lblShowStID.setText("---");
        jPanel3.add(lblShowStID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 240, 270));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 255));
        jLabel7.setText("Subject Details");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel8.setForeground(new java.awt.Color(204, 204, 255));
        jLabel8.setText("Subject ID :");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel9.setForeground(new java.awt.Color(204, 204, 255));
        jLabel9.setText("Subject Name :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        lblShowSubjectId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblShowSubjectId.setForeground(new java.awt.Color(204, 0, 0));
        lblShowSubjectId.setText("---");
        jPanel2.add(lblShowSubjectId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        lblShowSubjectName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblShowSubjectName.setForeground(new java.awt.Color(204, 0, 0));
        lblShowSubjectName.setText("---");
        jPanel2.add(lblShowSubjectName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 220, 270));

        pnlGradeDetails.setBackground(new java.awt.Color(5, 8, 28));
        pnlGradeDetails.setForeground(new java.awt.Color(255, 255, 255));
        pnlGradeDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        pnlGradeDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlGradeDetailsMouseClicked(evt);
            }
        });
        pnlGradeDetails.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pnlGradeDetailsKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(pnlGradeDetails);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 480, 140));

        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("Marks");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        txtMarksGrade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMarksGradeKeyReleased(evt);
            }
        });
        jPanel1.add(txtMarksGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 310, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 880, 470));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-back-24.png"))); // NOI18N
        jLabel14.setText("Student Grade Management System");
        jLabel14.setIconTextGap(20);
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, 30));

        jLabel15.setBackground(new java.awt.Color(0, 8, 28));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-account-24.png"))); // NOI18N
        jLabel15.setText("Welcome, Admin");
        jLabel15.setIconTextGap(6);
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, -1, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   
    private void loadStudentDetails(int studentId) {
    try {
        Connection con = DatabaseConnection.getConnection();
        String sql = "SELECT * FROM student WHERE student_id = ?";
        PreparedStatement stmt = con.prepareStatement(sql);
        stmt.setInt(1, studentId);
        ResultSet rs = stmt.executeQuery();

        if (rs.next()) {
            lblShowStID.setText(String.valueOf(rs.getInt("student_id")));
            lblShowtxtName.setText(rs.getString("student_name"));
            lblShowEmail.setText(rs.getString("email"));
            lblShowPhoneNo.setText(rs.getString("phone_number"));
        } else {
            lblShowStID.setText("---");
            lblShowtxtName.setText("---");
            lblShowEmail.setText("---");
            lblShowPhoneNo.setText("---");
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}
    private void loadSubjectDetails(int subjectId) {
    try {
        Connection con = DatabaseConnection.getConnection();
        String sql = "SELECT * FROM subject WHERE subject_id = ?";
        PreparedStatement stmt = con.prepareStatement(sql);
        stmt.setInt(1, subjectId);
        ResultSet rs = stmt.executeQuery();

        if (rs.next()) {
            lblShowSubjectId.setText(String.valueOf(rs.getInt("subject_id")));
            lblShowSubjectName.setText(rs.getString("subject_name"));
        } else {
            lblShowSubjectId.setText("---");
            lblShowSubjectName.setText("---");
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}


    private void clearStudentDetails() {
    lblShowStID.setText("---");
    lblShowtxtName.setText("---");
    lblShowEmail.setText("---");
    lblShowPhoneNo.setText("---");
}

private void clearSubjectDetails() {
    lblShowSubjectId.setText("---");
    lblShowSubjectName.setText("---");
}
    private void btnclearGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearGradeActionPerformed
        txtStudentIdGrade1.setText("");
        txtSubjectIdGrade.setText("");
        cmbGrade.setSelectedIndex(0);
        clearStudentDetails();
        clearSubjectDetails();// TODO add your handling code here:
    }//GEN-LAST:event_btnclearGradeActionPerformed

    private void btnUpdateGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateGradeActionPerformed
     if (!isFormValid()) return;

    try {
        Connection con = DatabaseConnection.getConnection();
        String sql = "UPDATE result_grade SET grade = ?, marks = ? WHERE student_id = ? AND subject_id = ?";
        PreparedStatement stmt = con.prepareStatement(sql);
        stmt.setString(1, cmbGrade.getSelectedItem().toString());
        stmt.setDouble(2, Double.parseDouble(txtMarksGrade.getText()));
        stmt.setInt(3, Integer.parseInt(txtStudentIdGrade1.getText()));
        stmt.setInt(4, Integer.parseInt(txtSubjectIdGrade.getText()));


        int result = stmt.executeUpdate();
        if (result > 0) {
            JOptionPane.showMessageDialog(this, "Grade updated.");
            loadResultData();
        } else {
            JOptionPane.showMessageDialog(this, "No matching grade record found.");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateGradeActionPerformed

    private void btnDeleteGrade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteGrade1ActionPerformed
    if (!isFormValid()) return;

    int choice = JOptionPane.showConfirmDialog(this,
        "Are you sure you want to delete this grade?",
        "Confirm Delete",
        JOptionPane.YES_NO_OPTION);

    if (choice != JOptionPane.YES_OPTION) return;

    try {
        Connection con = DatabaseConnection.getConnection();
        String sql = "DELETE FROM result_grade WHERE student_id = ? AND subject_id = ?";
        PreparedStatement stmt = con.prepareStatement(sql);
        stmt.setInt(1, Integer.parseInt(txtStudentIdGrade1.getText()));
        stmt.setInt(2, Integer.parseInt(txtSubjectIdGrade.getText()));

        int result = stmt.executeUpdate();
        if (result > 0) {
            JOptionPane.showMessageDialog(this, "Grade deleted.");
            loadResultData();
        } else {
            JOptionPane.showMessageDialog(this, "No grade record found to delete.");
        }
    } catch (Exception e) {
        e.printStackTrace();
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteGrade1ActionPerformed
    private boolean isFormValid() {
    if (txtStudentIdGrade1.getText().trim().isEmpty() ||
        txtSubjectIdGrade.getText().trim().isEmpty() ||
        cmbGrade.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(this, "Please fill all fields.");
        return false;
    }
    return true;
}

    private void btnAddGrade3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddGrade3ActionPerformed
     if (!isFormValid()) return;

    try {
        Connection con = DatabaseConnection.getConnection();
        String sql = "INSERT INTO result_grade (student_id, subject_id, marks, grade) VALUES (?, ?, ?, ?)";
        PreparedStatement stmt = con.prepareStatement(sql);

        stmt.setInt(1, Integer.parseInt(txtStudentIdGrade1.getText()));
        stmt.setInt(2, Integer.parseInt(txtSubjectIdGrade.getText()));
        stmt.setDouble(3, Double.parseDouble(txtMarksGrade.getText()));
        stmt.setString(4, cmbGrade.getSelectedItem().toString());


        int result = stmt.executeUpdate();

            if (result > 0) {
                JOptionPane.showMessageDialog(rootPane, "Data Add successfully");
                loadResultData();
            } else {
                JOptionPane.showMessageDialog(rootPane, "add failed. ID may not exist.");
            }
    } catch (SQLIntegrityConstraintViolationException e) {
        JOptionPane.showMessageDialog(this, "Grade already exists for this student and subject.");
    } catch (Exception e) {
        e.printStackTrace();
    }     // TODO add your handling code here:
    }//GEN-LAST:event_btnAddGrade3ActionPerformed

    private void txtSubjectIdGradeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSubjectIdGradeKeyReleased
     try {
            int subId = Integer.parseInt(txtSubjectIdGrade.getText().trim());
            loadSubjectDetails(subId);
        } catch (NumberFormatException ex) {
            clearSubjectDetails();
        }// TODO add your handling code here:
    }//GEN-LAST:event_txtSubjectIdGradeKeyReleased

    private void txtStudentIdGrade1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStudentIdGrade1KeyReleased
      try {
            int sid = Integer.parseInt(txtStudentIdGrade1.getText().trim());
            loadStudentDetails(sid);
        } catch (NumberFormatException ex) {
            clearStudentDetails();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentIdGrade1KeyReleased

    private void txtStudentIdGrade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentIdGrade1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentIdGrade1ActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        dashboardForm obj0 = new dashboardForm();
        obj0.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseClicked

    private void btnDeleteGrade1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteGrade1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteGrade1MouseClicked

    private void btnDeleteGrade1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteGrade1MouseEntered
    btnDeleteGrade1.setBackground(Color.RED);        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteGrade1MouseEntered

    private void btnDeleteGrade1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteGrade1MouseExited
    btnDeleteGrade1.setBackground(new Color(255, 204, 0));        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteGrade1MouseExited
    public void Tabledata(){
    int row = pnlGradeDetails.getSelectedRow();
        txtStudentIdGrade1.setText(pnlGradeDetails.getValueAt(row, 0).toString());
        txtSubjectIdGrade.setText(pnlGradeDetails.getValueAt(row, 1).toString());
        txtMarksGrade.setText(pnlGradeDetails.getValueAt(row, 2).toString());
        cmbGrade.setSelectedItem(pnlGradeDetails.getValueAt(row, 3).toString());

    }
    private void pnlGradeDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlGradeDetailsMouseClicked
         Tabledata(); // TODO add your handling code here:
    }//GEN-LAST:event_pnlGradeDetailsMouseClicked

    private void pnlGradeDetailsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pnlGradeDetailsKeyReleased
    Tabledata();        // TODO add your handling code here:
    }//GEN-LAST:event_pnlGradeDetailsKeyReleased

    private void txtMarksGradeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMarksGradeKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarksGradeKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gradeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gradeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gradeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gradeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gradeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddGrade3;
    private javax.swing.JButton btnDeleteGrade1;
    private javax.swing.JButton btnUpdateGrade;
    private javax.swing.JButton btnclearGrade;
    private javax.swing.JComboBox<String> cmbGrade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblShowEmail;
    private javax.swing.JLabel lblShowPhoneNo;
    private javax.swing.JLabel lblShowStID;
    private javax.swing.JLabel lblShowSubjectId;
    private javax.swing.JLabel lblShowSubjectName;
    private javax.swing.JLabel lblShowtxtName;
    private javax.swing.JTable pnlGradeDetails;
    private javax.swing.JTextField txtMarksGrade;
    private javax.swing.JTextField txtStudentIdGrade1;
    private javax.swing.JTextField txtSubjectIdGrade;
    // End of variables declaration//GEN-END:variables
}
