
import java.awt.Color;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Matheesha Anjana
 */
public class loginForm extends javax.swing.JFrame {

    /**
     * Creates new form loginForm
     */
    public loginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pnlLogin = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnSclear = new javax.swing.JButton();
        btnSLogin1 = new javax.swing.JButton();
        txtSPassword = new javax.swing.JPasswordField();
        btnLecturer = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnLLogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtLName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnSclear1 = new javax.swing.JButton();
        txtLPassword = new javax.swing.JPasswordField();
        btnStudent = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 8, 28));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/output-onlinepngtools.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 320));

        jButton1.setBackground(new java.awt.Color(204, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 50, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 390));

        jPanel2.setBackground(new java.awt.Color(15, 16, 66));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("Welcome");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 140, -1));

        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("User name");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));
        jPanel2.add(txtSname, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 250, -1));

        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("Password");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        btnSclear.setBackground(new java.awt.Color(15, 16, 66));
        btnSclear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSclear.setForeground(new java.awt.Color(255, 255, 255));
        btnSclear.setText("Clear");
        btnSclear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSclearActionPerformed(evt);
            }
        });
        jPanel2.add(btnSclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 120, -1));

        btnSLogin1.setBackground(new java.awt.Color(255, 204, 0));
        btnSLogin1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSLogin1.setForeground(new java.awt.Color(255, 255, 255));
        btnSLogin1.setText("Log in");
        btnSLogin1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSLogin1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnSLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 120, -1));

        txtSPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(txtSPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 250, -1));

        btnLecturer.setBackground(new java.awt.Color(15, 16, 66));
        btnLecturer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLecturer.setForeground(new java.awt.Color(255, 255, 255));
        btnLecturer.setText("LECTURER");
        btnLecturer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLecturer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLecturerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLecturerMouseExited(evt);
            }
        });
        btnLecturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLecturerActionPerformed(evt);
            }
        });
        jPanel2.add(btnLecturer, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 120, -1));

        pnlLogin.addTab("tab1", jPanel2);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLLogin.setBackground(new java.awt.Color(255, 204, 0));
        btnLLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLLogin.setText("Log in");
        btnLLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLLoginActionPerformed(evt);
            }
        });
        jPanel3.add(btnLLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 120, -1));

        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("Password");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));
        jPanel3.add(txtLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 250, -1));

        jLabel5.setForeground(new java.awt.Color(204, 204, 255));
        jLabel5.setText("User name");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 28)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 255));
        jLabel6.setText("Welcome");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 140, -1));

        btnSclear1.setBackground(new java.awt.Color(51, 51, 51));
        btnSclear1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSclear1.setForeground(new java.awt.Color(255, 255, 255));
        btnSclear1.setText("Clear");
        btnSclear1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSclear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSclear1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnSclear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 120, -1));

        txtLPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLPasswordActionPerformed(evt);
            }
        });
        jPanel3.add(txtLPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 250, -1));

        btnStudent.setBackground(new java.awt.Color(51, 51, 51));
        btnStudent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnStudent.setForeground(new java.awt.Color(204, 204, 255));
        btnStudent.setText("STUDENT");
        btnStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStudentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStudentMouseExited(evt);
            }
        });
        btnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentActionPerformed(evt);
            }
        });
        jPanel3.add(btnStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 120, -1));

        pnlLogin.addTab("tab2", jPanel3);

        getContentPane().add(pnlLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, -40, 380, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLecturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLecturerActionPerformed
       pnlLogin.setSelectedIndex(1); // TODO add your handling code here:
    }//GEN-LAST:event_btnLecturerActionPerformed

    private void btnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentActionPerformed
     pnlLogin.setSelectedIndex(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnStudentActionPerformed

    private void btnSclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSclearActionPerformed
    txtSname.setText("");
    txtSPassword.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_btnSclearActionPerformed

    private void btnLLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLLoginActionPerformed
    if (txtLName.getText().equals("admin") && txtLPassword.getText().equals("1234"
            + "")) 
    {
    dashboardForm obj1 = new dashboardForm();
    obj1.setVisible(true);
    this.setVisible(false);   
    }
    else
    {
        JOptionPane.showMessageDialog(this,"Invalid Username or Password");
    }         
               // TODO add your handling code here:
    }//GEN-LAST:event_btnLLoginActionPerformed

    private void btnSLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSLogin1ActionPerformed
    if (txtSname.getText().equals("user") && txtSPassword.getText().equals("1234")) 
    {
    studentDashboard obj2 = new studentDashboard();
    obj2.setVisible(true);
    this.setVisible(false);  
    }
    else
    {
        JOptionPane.showMessageDialog(this,"Invalid Username or Password");
    }          // TODO add your handling code here:
    }//GEN-LAST:event_btnSLogin1ActionPerformed

    private void btnSclear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSclear1ActionPerformed
     txtLName.setText("");
     txtLPassword.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_btnSclear1ActionPerformed

    private void txtSPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSPasswordActionPerformed

    private void txtLPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLPasswordActionPerformed

    private void btnStudentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudentMouseEntered
    // btnStudent.setBackground(new Color(15, 16, 66));        // TODO add your handling code here:
    }//GEN-LAST:event_btnStudentMouseEntered

    private void btnStudentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStudentMouseExited
     // btnStudent.setBackground(new Color(5 ,8 , 28));
       // TODO add your handling code here:
    }//GEN-LAST:event_btnStudentMouseExited

    private void btnLecturerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLecturerMouseEntered
    //btnLecturer.setBackground(new Color(15, 16, 66));       // TODO add your handling code here:
    }//GEN-LAST:event_btnLecturerMouseEntered

    private void btnLecturerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLecturerMouseExited
  // btnLecturer.setBackground(new Color(5, 8, 28));        // TODO add your handling code here:
    }//GEN-LAST:event_btnLecturerMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLLogin;
    private javax.swing.JButton btnLecturer;
    private javax.swing.JButton btnSLogin1;
    private javax.swing.JButton btnSclear;
    private javax.swing.JButton btnSclear1;
    private javax.swing.JButton btnStudent;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane pnlLogin;
    private javax.swing.JTextField txtLName;
    private javax.swing.JPasswordField txtLPassword;
    private javax.swing.JPasswordField txtSPassword;
    private javax.swing.JTextField txtSname;
    // End of variables declaration//GEN-END:variables
}
