
import connection.DatabaseConnection;
import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.sql.Connection;
import java.sql.DriverManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Matheesha Anjana
 */
public class RecorrectionForm extends javax.swing.JFrame {

    /**
     * Creates new form RecorrectionForm
     */
    public RecorrectionForm() {
        initComponents();
        loadRecorrectionData();
    }
    
    private void loadRecorrectionData() {
    // Define column names
    String[] columnNames = {"ID", "Student ID", "Subject ID", "Comment", "Status"};

    // Create a new table model with column names
    DefaultTableModel model = new DefaultTableModel(columnNames, 0);
    pnlRecorrectionData.setModel(model); // Set model to your JTable

    try {
        Connection con = DatabaseConnection.getConnection();
        String sql = "SELECT recorrection_id, student_id, subject_id, comment, status FROM recorrection";
        PreparedStatement stmt = con.prepareStatement(sql);
        ResultSet rs = stmt.executeQuery();

        while (rs.next()) {
            Object[] row = {
                rs.getInt("recorrection_id"),
                rs.getInt("student_id"),
                rs.getInt("subject_id"),
                rs.getString("comment"),
                rs.getString("status")
            };
            model.addRow(row);
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}

    private void loadStudentDetails(int studentId) {
    try {
        Connection con = DatabaseConnection.getConnection();
        String sql = "SELECT * FROM student WHERE student_id = ?";
        PreparedStatement stmt = con.prepareStatement(sql);
        stmt.setInt(1, studentId);
        ResultSet rs = stmt.executeQuery();

        if (rs.next()) {
            lblShowStID.setText(String.valueOf(rs.getInt("student_id")));
            lblShowtxtName.setText(rs.getString("student_name"));
            lblShowEmail.setText(rs.getString("email"));
            lblShowPhoneNo.setText(rs.getString("phone_number"));
        } else {
            lblShowStID.setText("---");
            lblShowtxtName.setText("---");
            lblShowEmail.setText("---");
            lblShowPhoneNo.setText("---");
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}
    private void loadSubjectDetails(int subjectId) {
    try {
        Connection con = DatabaseConnection.getConnection();
        String sql = "SELECT * FROM subject WHERE subject_id = ?";
        PreparedStatement stmt = con.prepareStatement(sql);
        stmt.setInt(1, subjectId);
        ResultSet rs = stmt.executeQuery();

        if (rs.next()) {
            lblShowSubjectId.setText(String.valueOf(rs.getInt("subject_id")));
            lblShowSubjectName.setText(rs.getString("subject_name"));
        } else {
            lblShowSubjectId.setText("---");
            lblShowSubjectName.setText("---");
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtSubjectIdRecorection = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtStudentIdRecorection = new javax.swing.JTextField();
        btnClearRecorection = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtCommentRecorection = new javax.swing.JTextField();
        btnComment = new javax.swing.JLabel();
        btnRequest1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        lblShowtxtName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblShowEmail = new javax.swing.JLabel();
        lblShowPhoneNo = new javax.swing.JLabel();
        lblShowStID = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblShowSubjectId = new javax.swing.JLabel();
        lblShowSubjectName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlRecorrectionData = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-back-24.png"))); // NOI18N
        jLabel8.setText("Student Grade Management System");
        jLabel8.setIconTextGap(20);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, 30));

        jLabel9.setBackground(new java.awt.Color(0, 8, 28));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-account-24.png"))); // NOI18N
        jLabel9.setText("Welcome, User");
        jLabel9.setIconTextGap(6);
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, 140, 30));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 50));

        jPanel2.setBackground(new java.awt.Color(5, 8, 28));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSubjectIdRecorection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSubjectIdRecorectionActionPerformed(evt);
            }
        });
        txtSubjectIdRecorection.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSubjectIdRecorectionKeyReleased(evt);
            }
        });
        jPanel2.add(txtSubjectIdRecorection, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 250, -1));

        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("Enter your index :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("Enter Subject ID :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        txtStudentIdRecorection.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtStudentIdRecorectionKeyReleased(evt);
            }
        });
        jPanel2.add(txtStudentIdRecorection, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 250, -1));

        btnClearRecorection.setBackground(new java.awt.Color(5, 8, 28));
        btnClearRecorection.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClearRecorection.setForeground(new java.awt.Color(255, 255, 255));
        btnClearRecorection.setText("Clear");
        btnClearRecorection.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClearRecorection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearRecorectionActionPerformed(evt);
            }
        });
        jPanel2.add(btnClearRecorection, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 250, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("Recorrection");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, -1, -1));

        txtCommentRecorection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCommentRecorectionActionPerformed(evt);
            }
        });
        jPanel2.add(txtCommentRecorection, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 250, 50));

        btnComment.setForeground(new java.awt.Color(204, 204, 255));
        btnComment.setText("Comment :");
        jPanel2.add(btnComment, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        btnRequest1.setBackground(new java.awt.Color(255, 204, 0));
        btnRequest1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRequest1.setForeground(new java.awt.Color(255, 255, 255));
        btnRequest1.setText("Request");
        btnRequest1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRequest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequest1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnRequest1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 250, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 350, 490));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(5, 8, 28));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblShowtxtName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblShowtxtName.setForeground(new java.awt.Color(204, 0, 0));
        lblShowtxtName.setText("---");
        jPanel6.add(lblShowtxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 20));

        jLabel5.setForeground(new java.awt.Color(204, 204, 255));
        jLabel5.setText("Phone No :");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 255));
        jLabel10.setText("Student Details");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel11.setForeground(new java.awt.Color(204, 204, 255));
        jLabel11.setText("Student Name :");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel12.setForeground(new java.awt.Color(204, 204, 255));
        jLabel12.setText("Email :");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel13.setForeground(new java.awt.Color(204, 204, 255));
        jLabel13.setText("Student ID :");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        lblShowEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblShowEmail.setForeground(new java.awt.Color(204, 0, 0));
        lblShowEmail.setText("---");
        jPanel6.add(lblShowEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        lblShowPhoneNo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblShowPhoneNo.setForeground(new java.awt.Color(204, 0, 0));
        lblShowPhoneNo.setText("---");
        jPanel6.add(lblShowPhoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        lblShowStID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblShowStID.setForeground(new java.awt.Color(204, 0, 0));
        lblShowStID.setText("---");
        jPanel6.add(lblShowStID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 240, 270));

        jPanel7.setBackground(new java.awt.Color(5, 8, 28));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 255));
        jLabel14.setText("Subject Details");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel15.setForeground(new java.awt.Color(204, 204, 255));
        jLabel15.setText("Subject ID :");
        jPanel7.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jLabel16.setForeground(new java.awt.Color(204, 204, 255));
        jLabel16.setText("Subject Name :");
        jPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        lblShowSubjectId.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblShowSubjectId.setForeground(new java.awt.Color(204, 0, 0));
        lblShowSubjectId.setText("---");
        jPanel7.add(lblShowSubjectId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        lblShowSubjectName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblShowSubjectName.setForeground(new java.awt.Color(204, 0, 0));
        lblShowSubjectName.setText("---");
        jPanel7.add(lblShowSubjectName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 230, 270));

        pnlRecorrectionData.setBackground(new java.awt.Color(5, 8, 28));
        pnlRecorrectionData.setForeground(new java.awt.Color(255, 255, 255));
        pnlRecorrectionData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(pnlRecorrectionData);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 490, 170));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 530, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        studentDashboard obj0 = new studentDashboard();
        obj0.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    private void txtSubjectIdRecorectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSubjectIdRecorectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubjectIdRecorectionActionPerformed

    private void btnClearRecorectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearRecorectionActionPerformed
    txtStudentIdRecorection.setText("");
    txtSubjectIdRecorection.setText("");
    txtCommentRecorection.setText("");
    }//GEN-LAST:event_btnClearRecorectionActionPerformed

    private void txtCommentRecorectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommentRecorectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCommentRecorectionActionPerformed
    private boolean isFormValid() {
    if (txtStudentIdRecorection.getText().isEmpty() || 
        txtSubjectIdRecorection.getText().isEmpty() || 
        txtCommentRecorection.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please fill all fields.");
        return false;
    }
    return true;
}

    private void btnRequest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequest1ActionPerformed
           if (!isFormValid()) return;

try {
    Connection con = DatabaseConnection.getConnection();
    String sql = "INSERT INTO recorrection (student_id, subject_id, comment) VALUES (?, ?, ?)";
    PreparedStatement stmt = con.prepareStatement(sql);

    stmt.setInt(1, Integer.parseInt(txtStudentIdRecorection.getText()));
    stmt.setInt(2, Integer.parseInt(txtSubjectIdRecorection.getText()));
    stmt.setString(3, txtCommentRecorection.getText());

    int result = stmt.executeUpdate();

    if (result > 0) {
        JOptionPane.showMessageDialog(rootPane, "Recorrection request submitted successfully.");
        loadRecorrectionData(); // method to refresh JTable if needed
    } else {
        JOptionPane.showMessageDialog(rootPane, "Request failed. ID may not exist.");
    }
} catch (SQLIntegrityConstraintViolationException e) {
    JOptionPane.showMessageDialog(this, "Request already exists or invalid student/subject ID.");
} catch (Exception e) {
    e.printStackTrace();
}
// TODO add your handling code here:
    }//GEN-LAST:event_btnRequest1ActionPerformed

    private void txtStudentIdRecorectionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStudentIdRecorectionKeyReleased
     try {
            int sid = Integer.parseInt(txtStudentIdRecorection.getText().trim());
            loadStudentDetails(sid);
        } catch (NumberFormatException ex) {
            clearStudentDetails();
        }             // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentIdRecorectionKeyReleased
     private void clearSubjectDetails() {
    lblShowSubjectId.setText("---");
    lblShowSubjectName.setText("---");
     }
     private void clearStudentDetails() {
    lblShowStID.setText("---");
    lblShowtxtName.setText("---");
    lblShowEmail.setText("---");
    lblShowPhoneNo.setText("---");
     }
    private void txtSubjectIdRecorectionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSubjectIdRecorectionKeyReleased
      try {
            int subId = Integer.parseInt(txtSubjectIdRecorection.getText().trim());
            loadSubjectDetails(subId);
        } catch (NumberFormatException ex) {
            clearSubjectDetails();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_txtSubjectIdRecorectionKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecorrectionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecorrectionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecorrectionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecorrectionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecorrectionForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearRecorection;
    private javax.swing.JLabel btnComment;
    private javax.swing.JButton btnRequest1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblShowEmail;
    private javax.swing.JLabel lblShowPhoneNo;
    private javax.swing.JLabel lblShowStID;
    private javax.swing.JLabel lblShowSubjectId;
    private javax.swing.JLabel lblShowSubjectName;
    private javax.swing.JLabel lblShowtxtName;
    private javax.swing.JTable pnlRecorrectionData;
    private javax.swing.JTextField txtCommentRecorection;
    private javax.swing.JTextField txtStudentIdRecorection;
    private javax.swing.JTextField txtSubjectIdRecorection;
    // End of variables declaration//GEN-END:variables
}
