import connection.DatabaseConnection;
import java.awt.print.PrinterException;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.sql.Connection;
import java.sql.DriverManager;
import java.text.MessageFormat;
import javax.swing.JTable;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Matheesha Anjana
 */
public class studentReport extends javax.swing.JFrame {

    /**
     * Creates new form studentReport
     */
    public studentReport() {
        initComponents();
        setupReportTable();
    }
    private void setupReportTable() {
    DefaultTableModel model = new DefaultTableModel();
    model.setColumnIdentifiers(new String[] {
        "Student ID", "Student Name", "Subject ID", "Subject Name", "Grade"
    });
    pnlStudentReport.setModel(model);}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cmbStudenId = new javax.swing.JComboBox<>();
        btnSearchReport = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlStudentReport = new javax.swing.JTable();
        bynPrint = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(5, 8, 28));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 255));
        jLabel10.setText("Print Your Result Sheet");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, -1, 20));

        cmbStudenId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cmbStudenId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStudenIdActionPerformed(evt);
            }
        });
        jPanel2.add(cmbStudenId, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 190, 30));

        btnSearchReport.setBackground(new java.awt.Color(255, 204, 0));
        btnSearchReport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSearchReport.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchReport.setText("Search");
        btnSearchReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchReportActionPerformed(evt);
            }
        });
        jPanel2.add(btnSearchReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 110, 30));

        pnlStudentReport.setBackground(new java.awt.Color(5, 8, 28));
        pnlStudentReport.setForeground(new java.awt.Color(255, 255, 255));
        pnlStudentReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        pnlStudentReport.setGridColor(new java.awt.Color(5, 8, 28));
        pnlStudentReport.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(pnlStudentReport);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 810, 280));

        bynPrint.setBackground(new java.awt.Color(255, 204, 0));
        bynPrint.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        bynPrint.setForeground(new java.awt.Color(255, 255, 255));
        bynPrint.setText("Print");
        bynPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bynPrintActionPerformed(evt);
            }
        });
        jPanel2.add(bynPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(722, 360, 120, -1));

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 255));
        jLabel11.setText("Select Your Index :");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 870, 400));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-back-24.png"))); // NOI18N
        jLabel8.setText("Student Grade Management System");
        jLabel8.setIconTextGap(20);
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, 30));

        jLabel9.setBackground(new java.awt.Color(0, 8, 28));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-account-24.png"))); // NOI18N
        jLabel9.setText("Welcome, User");
        jLabel9.setIconTextGap(6);
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 140, 30));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchReportActionPerformed
     String studentId = cmbStudenId.getSelectedItem().toString().trim();

try {
    Connection con = DatabaseConnection.getConnection();

    String sql = "SELECT rg.student_id, s.student_name, rg.subject_id, sub.subject_name, rg.grade " +
                 "FROM result_grade rg " +
                 "JOIN student s ON rg.student_id = s.student_id " +
                 "JOIN subject sub ON rg.subject_id = sub.subject_id " +
                 "WHERE rg.student_id = ?";

    PreparedStatement pstmt = con.prepareStatement(sql);
    pstmt.setString(1, studentId);

    ResultSet rs = pstmt.executeQuery();

    DefaultTableModel model = (DefaultTableModel) pnlStudentReport.getModel();
    model.setRowCount(0); // Clear previous rows

    if (!rs.isBeforeFirst()) {
        JOptionPane.showMessageDialog(this, "No results found.");
        return;
    }

    while (rs.next()) {
        model.addRow(new Object[]{
            rs.getInt("student_id"),
            rs.getString("student_name"),
            rs.getInt("subject_id"),
            rs.getString("subject_name"),
            rs.getString("grade")
        });
    }

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Error loading results: " + e.getMessage());
}
     
          // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchReportActionPerformed

    private void cmbStudenIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStudenIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbStudenIdActionPerformed

    private void bynPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bynPrintActionPerformed
    try {
        // Get selected student info from table (first row only)
        String studentId = "";
        String studentName = "";

        if (pnlStudentReport.getRowCount() > 0) {
            studentId = pnlStudentReport.getValueAt(0, 0).toString();
            studentName = pnlStudentReport.getValueAt(0, 1).toString();
        }

        // Create header and footer text
        MessageFormat header = new MessageFormat("Result Sheeet \n - Student ID: " + studentId + "   Name: " + studentName);
        MessageFormat footer = new MessageFormat("Thank you");

        // Print the table
        boolean complete = pnlStudentReport.print(JTable.PrintMode.FIT_WIDTH, header, footer);

        if (complete) {
            JOptionPane.showMessageDialog(this, "Printing Complete", "Print", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Printing Cancelled", "Print", JOptionPane.WARNING_MESSAGE);
        }

    } catch (PrinterException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Printing Failed: " + ex.getMessage(), "Print Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_bynPrintActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        studentDashboard obj0 = new studentDashboard();
        obj0.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSearchReport;
    private javax.swing.JButton bynPrint;
    private javax.swing.JComboBox<String> cmbStudenId;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable pnlStudentReport;
    // End of variables declaration//GEN-END:variables
}
