
import connection.DatabaseConnection;
import java.awt.Color;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.sql.Connection;
import java.sql.DriverManager;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Matheesha Anjana
 */
public class studentForm extends javax.swing.JFrame {

    /**
     * Creates new form studentForm
     */
    public studentForm() {
        initComponents();
        loadStudentData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtStudentName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnUpdateStudent = new javax.swing.JButton();
        btnclearStudent = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtStudentPhoneNo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnDeleteStudent = new javax.swing.JButton();
        btnAddStudent = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtStudentId1 = new javax.swing.JTextField();
        txtStudentEmail1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlStudentDetail = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(5, 8, 28));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("Student ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));
        jPanel1.add(txtStudentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 290, -1));

        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("Student Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        btnUpdateStudent.setBackground(new java.awt.Color(255, 204, 0));
        btnUpdateStudent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdateStudent.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateStudent.setText("Update");
        btnUpdateStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStudentActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdateStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 130, -1));

        btnclearStudent.setBackground(new java.awt.Color(5, 8, 28));
        btnclearStudent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnclearStudent.setForeground(new java.awt.Color(255, 255, 255));
        btnclearStudent.setText("Clear");
        btnclearStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnclearStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclearStudentActionPerformed(evt);
            }
        });
        jPanel1.add(btnclearStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 290, -1));

        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("Email");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));
        jPanel1.add(txtStudentPhoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 290, -1));

        jLabel5.setForeground(new java.awt.Color(204, 204, 255));
        jLabel5.setText("Phone No");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        btnDeleteStudent.setBackground(new java.awt.Color(255, 204, 0));
        btnDeleteStudent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteStudent.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteStudent.setText("Delete");
        btnDeleteStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeleteStudent.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnDeleteStudentMouseMoved(evt);
            }
        });
        btnDeleteStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteStudentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteStudentMouseExited(evt);
            }
        });
        btnDeleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteStudentActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeleteStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 140, -1));

        btnAddStudent.setBackground(new java.awt.Color(255, 204, 0));
        btnAddStudent.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddStudent.setForeground(new java.awt.Color(255, 255, 255));
        btnAddStudent.setText("Add");
        btnAddStudent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudentActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 290, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("Student Details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        txtStudentId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentId1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtStudentId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 290, -1));
        jPanel1.add(txtStudentEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 290, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 350, 500));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlStudentDetail.setBackground(new java.awt.Color(5, 8, 28));
        pnlStudentDetail.setForeground(new java.awt.Color(255, 255, 255));
        pnlStudentDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        pnlStudentDetail.setFocusable(false);
        pnlStudentDetail.setRowHeight(25);
        pnlStudentDetail.setSelectionBackground(new java.awt.Color(204, 0, 0));
        pnlStudentDetail.setSelectionForeground(new java.awt.Color(255, 255, 255));
        pnlStudentDetail.getTableHeader().setReorderingAllowed(false);
        pnlStudentDetail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlStudentDetailMouseClicked(evt);
            }
        });
        pnlStudentDetail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pnlStudentDetailKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(pnlStudentDetail);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, 440));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 530, 500));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-back-24.png"))); // NOI18N
        jLabel6.setText("Student Grade Management System");
        jLabel6.setIconTextGap(20);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, 30));

        jLabel7.setBackground(new java.awt.Color(0, 8, 28));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-account-24.png"))); // NOI18N
        jLabel7.setText("Welcome, Admin");
        jLabel7.setIconTextGap(6);
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, -1, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public boolean validateForm(){
     boolean status = false;
     if(txtStudentName.getText().equals("") ||
             txtStudentPhoneNo.getText().equals("") ||
             txtStudentPhoneNo.getText().equals(""))
     {
       status = true;
     }
     return status;
    }
    
    private void loadStudentData() {
    DefaultTableModel model = (DefaultTableModel) pnlStudentDetail.getModel();

    // ✅ Set column headers
    model.setColumnIdentifiers(new String[] {
        "Student ID", "Student Name", "Email", "Phone Number"
    });

    model.setRowCount(0); // clear existing data

    try {
        Connection con = DatabaseConnection.getConnection();
        String sql = "SELECT * FROM student";
        Statement stmt = con.createStatement();
        ResultSet rs = stmt.executeQuery(sql);

        while (rs.next()) {
            String id = rs.getString("student_id");
            String name = rs.getString("student_name");
            String email = rs.getString("email");
            String number = rs.getString("phone_number");

            model.addRow(new Object[]{id, name, email, number});
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error loading student data: " + e.getMessage());
    }
}

    private void btnUpdateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateStudentActionPerformed
        if (validateForm()) {
        JOptionPane.showMessageDialog(rootPane, "Please fill all fields");
    } else {
        try {
            Connection con = DatabaseConnection.getConnection();
            String sql = "UPDATE student SET student_name = ?, email = ?, phone_number = ? WHERE student_id = ?";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1, txtStudentName.getText().trim());
            stmt.setString(2, txtStudentEmail1.getText().trim());
            stmt.setString(3, txtStudentPhoneNo.getText().trim());
            stmt.setString(4, txtStudentId1.getText().trim());

            int result = stmt.executeUpdate();

            if (result > 0) {
                JOptionPane.showMessageDialog(rootPane, "Data updated successfully");
                loadStudentData();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Update failed. ID may not exist.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateStudentActionPerformed
    }
    private void btnclearStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclearStudentActionPerformed
        txtStudentId1.setText("");
        txtStudentName.setText("");
        txtStudentEmail1.setText("");
        txtStudentPhoneNo.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_btnclearStudentActionPerformed

    private void btnDeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteStudentActionPerformed
     String id = txtStudentId1.getText().trim();
    if (id.equals("")) {
        JOptionPane.showMessageDialog(rootPane, "Please enter Student ID to delete");
    } else {
        int confirm = JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to delete this student?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                Connection con = DatabaseConnection.getConnection();
                String sql = "DELETE FROM student WHERE student_id = ?";
                PreparedStatement stmt = con.prepareStatement(sql);
                stmt.setString(1, id);

                int result = stmt.executeUpdate();

                if (result > 0) {
                    JOptionPane.showMessageDialog(rootPane, "Student deleted successfully");
                    loadStudentData();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Delete failed. ID not found.");
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Error: " + e.getMessage());
            }
        }
    }        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteStudentActionPerformed

    private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddStudentActionPerformed
        if(validateForm())
        {
            JOptionPane.showMessageDialog(rootPane,""+"Please fill all");
        }else
        {
            Connection con = DatabaseConnection.getConnection();
            if(validateForm())
        {
            JOptionPane.showMessageDialog(rootPane,""+"Please fill all");
        }else
        {
            try{
                
                String sql = "INSERT INTO student (student_name, email, phone_number) VALUES (?, ?, ?)";
                PreparedStatement stmt =con.prepareStatement(sql);
                stmt = con.prepareStatement(sql);
                stmt.setString(1, txtStudentName.getText().trim());
                stmt.setString(2, txtStudentEmail1.getText().trim());
                stmt.setString(3, txtStudentPhoneNo.getText().trim());

                int result = stmt.executeUpdate();

                if(result >0)
                {
                    JOptionPane.showMessageDialog(rootPane,"Data saved");
                    loadStudentData();
                }else{
                    JOptionPane.showMessageDialog(rootPane,"Data saved faild");
                }
                
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane,""+e);
            }
        }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddStudentActionPerformed

    private void txtStudentId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentId1ActionPerformed

    private void btnDeleteStudentMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteStudentMouseMoved
            // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteStudentMouseMoved

    private void btnDeleteStudentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteStudentMouseEntered
    btnDeleteStudent.setBackground(Color.RED);        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteStudentMouseEntered

    private void btnDeleteStudentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteStudentMouseExited
     btnDeleteStudent.setBackground(new Color(255, 204, 0));            // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteStudentMouseExited
    public void Tabledata(){
    int row = pnlStudentDetail.getSelectedRow();
        txtStudentId1.setText(pnlStudentDetail.getValueAt(row, 0).toString());
        txtStudentName.setText(pnlStudentDetail.getValueAt(row, 1).toString());
        txtStudentEmail1.setText(pnlStudentDetail.getValueAt(row, 2).toString());
        txtStudentPhoneNo.setText(pnlStudentDetail.getValueAt(row, 3).toString());
        
    }
    private void pnlStudentDetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlStudentDetailMouseClicked
          Tabledata();  // TODO add your handling code here:
    }//GEN-LAST:event_pnlStudentDetailMouseClicked

    private void pnlStudentDetailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pnlStudentDetailKeyReleased
       Tabledata();        // TODO add your handling code here:
    }//GEN-LAST:event_pnlStudentDetailKeyReleased

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
    dashboardForm obj0 = new dashboardForm();
     obj0.setVisible(true);
    this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddStudent;
    private javax.swing.JButton btnDeleteStudent;
    private javax.swing.JButton btnUpdateStudent;
    private javax.swing.JButton btnclearStudent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable pnlStudentDetail;
    private javax.swing.JTextField txtStudentEmail1;
    private javax.swing.JTextField txtStudentId1;
    private javax.swing.JTextField txtStudentName;
    private javax.swing.JTextField txtStudentPhoneNo;
    // End of variables declaration//GEN-END:variables
}
